/**
 * Copyright 2026 Bruce Ide
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * This is a line-by-line processor that reans lines of code from your
 * program and emits lines of code out. If it encounters the
 * annotation [[StartModule(ModuleName)]] it will create a NB_MODULE
 * line with ModuleName as the name. If it encounters a [[PythonApi]]
 * annotation, it will (attempt to) create a nanobind API for all the
 * classes in the index.json file. YMMV.
 *
 * An index.json file must exist and be passed to this program on the
 * command line. The index is generated by the IndexCode program in this
 * directory.
 */

#include <boost/program_options.hpp>
#include <fr/codegen/data.h>
#include <fr/codegen/drivers.h>
#include <fr/codegen/LblFilter.h>
#include <fr/codegen/LblMiniParser.h>
#include <fr/codegen/LblEmitFunctions.h>
#include <fr/codegen/GenerateNanobind.h>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <vector>

void printHelp(boost::program_options::options_description &desc) {
  std::cout << "This program reads a .cpp file line by line looking for" << std::endl;
  std::cout << "[[StartModule (ModuleName)]] and [[PythonApi]] annotations." << std::endl;
  std::cout << "It will attempt to generate a nanobind API for any classes it" << std::endl;
  std::cout << "finds in an index.json file generated by IndexCode. See the" << std::endl;
  std::cout << "examples/config_file example that ships with this project for" << std::endl;
  std::cout << "general details." << std::endl;
  std::cout << desc << std::endl;
}

int main(int argc, char *argv[]) {
  using namespace fr::codegen;

  std::string source;
  std::string output;
  std::string index;

  boost::program_options::options_description desc("Options:");
  boost::program_options::variables_map vm;

  desc.add_options()
    ("source,s",
     boost::program_options::value<std::string>(&source),
     "Source .cpp file to use as a template.")
    ("index,i",
     boost::program_options::value<std::string>(&index),
     "Index file containing objects to generate API for")
    ("output,o",
     boost::program_options::value<std::string>(&output),
     "Output to write modified source file to")
    ;

  boost::program_options::store(boost::program_options::parse_command_line(argc, argv, desc), vm);
  boost::program_options::notify(vm);

  if (!vm.count("source") || !vm.count("index") || !vm.count("output")) {
    printHelp(desc);
    exit(1);
  }

  std::map<std::string, std::shared_ptr<EnumData>> enumMap;
  std::map<std::string, std::shared_ptr<ClassData>> classMap;

  std::cout << "Reading index " << index << "..." << std::endl;
  std::ifstream indexStream(index);
  {
    cereal::JSONInputArchive archive(indexStream);
    archive(enumMap);
    archive(classMap);
  }

  std::cout << "Setting up line by line processor..." << std::endl;

  LblReader reader(source);

  fr::codegen::miniparser::LblMiniparser parser;
  parser.subscribeTo(reader);
  
  LblEmitModuleStart moduleProcessor(classMap);
  moduleProcessor.subscribeTo(parser);

  moduleProcessor.startModule.connect([](const std::string& name) {
    std::cout << "Starting module " << name << std::endl;
  });
  
  LblEmitPythonApi apiProcessor(classMap);
  apiProcessor.subscribeTo(moduleProcessor);
  
  apiProcessor.processingClass.connect([](const std::string& name) {
    std::cout << "Processing class " << name << std::endl;
  });

  apiProcessor.processingConstructor.connect([](){
    std::cout << "Processing constructor" << std::endl;
  });

  apiProcessor.processingMethod.connect([](const std::string& name) {
    std::cout << "Processing method " << name << std::endl;    
  });

  apiProcessor.processingMember.connect([](const std::string& name) {
    std::cout << "Processing member " << name << std::endl;
  });

  LblWriter writer(output);
  writer.subscribeTo(apiProcessor);

  reader.process();

  std::cout << "Processing complete" << std::endl;
  exit(0);
}
